const AVATAR_COUNT = 6;

const PHOTOS_COUNT = 25;

const MAX_SCALE = 100;
const MIN_SCALE = 25;
const SCALE_STEP = 25;

const MAX_COMMENT_LENGTH = 140;
const MAX_HASHTAG_COUNT = 5;
const MAX_HASHTAG_LENGTH = 20;

const LIKES_RANGE_FROM = 15;
const LIKES_RANGE_TO = 200;

const COMMENTS_RANGE_FROM = 2;
const COMMENTS_RANGE_TO = 20;

const COUNT_OF_LOADED_COMMENTS = 5;

export {
  AVATAR_COUNT,
  MAX_SCALE,
  MIN_SCALE,
  SCALE_STEP,
  MAX_COMMENT_LENGTH,
  MAX_HASHTAG_LENGTH,
  MAX_HASHTAG_COUNT,
  PHOTOS_COUNT,
  LIKES_RANGE_TO,
  LIKES_RANGE_FROM,
  COUNT_OF_LOADED_COMMENTS,
  COMMENTS_RANGE_TO,
  COMMENTS_RANGE_FROM
};
